### ISSUE TITLE
create the channel if it doesn't exist 

### ISSUE THREAD

**Issue by asafwat** [OctopusDeploy/create-release-action#322]
when we pass the channel name with the release, the action should check if the channel exist and if not it should create it.

at the moment if the channels doesn't exit, action will fail with this error

```
"Cannot find the channel with name or id 'test' in test-project. Please check the spelling and that you have permissions to view it. Please use Configuration > Test Permissions to confirm.
Exit code: -1"

```
we are using the octopus cli action first to create the channel then pass it to the create release action as a work around.

**Comment by borland** [comment]
Hi asafwat

Creating Channels in Octopus Deploy requires configuration, such as selection of a Lifecycle and Version rules. This needs careful consideration and is not something which can safely be done in an automated task such as create-release-action.
This is not a feature which we can implement, so I will close this Issue.

If you have not already seen it, you may find the Octopus documentation around Channels useful:
https://octopus.com/docs/releases/channels

Kind regards

Orion Edwards (Senior Software Engineer at Octopus)
