### ISSUE TITLE
Support pushing Jira information to Octopus

### ISSUE THREAD

**Issue by peterv-work** [OctopusDeploy/create-release-action#349]
**Is your feature request related to a problem? Please describe.**

Currently the Octopus documentation around [Jira integration](https://octopus.com/docs/releases/issue-tracking/jira) state
> The ability to push the build information to Octopus, which is required for Jira integration, is currently only available in the official Octopus plugins: JetBrains TeamCity, Atlassian Bamboo, Azure DevOps, Jenkins Octopus Deploy Plugin.

This seems to suggest that I can't have Jira integration if I am using this plugin in my Github Actions.

**Describe the solution you'd like**

This plugin is able to push the appropriate "build information" to Octopus.

**Describe alternatives you've considered**

n/a

**Additional context**
n/a

**Comment by hnrkndrssn** [comment]
Hey @peterv-work,

Thanks for getting in touch. 

We actually have a [push build information action](https://github.com/OctopusDeploy/push-build-information-action) that you can use to push Jira information to Octopus.

I'll make a note to get the docs page updated to mention this.

Thanks,
Henrik
