### ISSUE TITLE
progress: true in v2

### ISSUE THREAD

**Issue by olsh** [OctopusDeploy/create-release-action#351]
In v1 of the action, it was possible to wait for deployment and fail build if the deployment failed. `progress: true`
If I understood the page correctly, there is no such a possibility in v2 of the action.
https://github.com/OctopusDeploy/create-release-action/blob/main/migration-guide.md

Are there alternatives to achieve that?

**Comment by gazab** [comment]
We could also use this option. Any specific reason why it was removed?

**Comment by olsh** [comment]
There was added new action for this.
`OctopusDeploy/await-task-action@v3`

You can find examples in this post
https://octopus.com/blog/github-actions-for-octopus-deploy-v3
