### ISSUE TITLE
Update actions to use Node.js 16

### ISSUE THREAD

**Issue by tane-wahyunadi-deltatre** [OctopusDeploy/create-release-action#352]
Hi,

Could you please update the action to use Node.js 16? I believe you are already aware of this warning.
![image](https://user-images.githubusercontent.com/110435660/197268783-05c48cc8-316c-4f24-9cda-6a489af0413b.png)

Thanks.

**Comment by benjimac93** [comment]
There is a PR open for this: https://github.com/OctopusDeploy/create-release-action/pull/350

**Comment by ann-mwangi** [comment]
Done in the [latest release](https://github.com/OctopusDeploy/create-release-action/releases/tag/v2.1.0).
