### ISSUE TITLE
GitHub unable to find version `v3` of OctopusDeploy/create-release-action

### ISSUE THREAD

**Issue by Porter-dm** [OctopusDeploy/create-release-action#360]
**Describe the bug**
GitHub fails to find create-release-action@v3

**To Reproduce**
1. In an existing GitHub workflow, add a step which uses `OctopusDeploy/create-release-action@v3`.  (This was changed from `@v2` to `@v3` in the README.md in [the latest commit on Dec 5](https://github.com/OctopusDeploy/create-release-action/commit/982b7d4ab80a7c5f43aa38a90c9092c2b72768e8).)
2. GitHub fails to initialize the job, giving the error
>Unable to resolve action `OctopusDeploy/create-release-action@v3`, unable to find version `v3`

**Expected behavior**
GitHub can find `@v3` version of create-release-actions

**Comment by ann-mwangi** [comment]
The team is preparing for the V3 release next week, so the new version details has surfaced in the prep work. 

We appreciate you updating to the latest version, but bear with us as we make the final preparations. For the meantime you can continue using the V2.

**Comment by Porter-dm** [comment]
The reason I ran into trouble in the first place is that the [official documentation in the GitHub Marketplace](https://github.com/marketplace/actions/create-release-in-octopus-deploy) says to use `v3`.

I had never used this action before, and following the documented instructions wasn't working for me.
